"""empty message

Revision ID: 5081f0422d81
Revises: 6ebfdd8946a9
Create Date: 2023-11-02 21:13:46.347341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5081f0422d81'
down_revision: Union[str, None] = '6ebfdd8946a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('articles', sa.Integer(), nullable=True),
    sa.Column('topics', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articles'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topics'], ['topics.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('topics')
    # ### end Alembic commands ###
