"""empty message

Revision ID: 6ed4e1619563
Revises: ba58627f732a
Create Date: 2023-11-02 21:22:26.888159

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ed4e1619563"
down_revision: Union[str, None] = "ba58627f732a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_to_topic",
        sa.Column("articles", sa.Integer(), nullable=True),
        sa.Column("topics", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["articles"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topics"],
            ["topics.id"],
        ),
    )
    op.drop_table("article")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("articles", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("topics", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["articles"], ["articles.id"], name="article_articles_fkey"
        ),
        sa.ForeignKeyConstraint(["topics"], ["topics.id"], name="article_topics_fkey"),
    )
    op.drop_table("article_to_topic")
    # ### end Alembic commands ###
