"""empty message

Revision ID: a1fd3b694fab
Revises: b943530bccb6
Create Date: 2023-11-15 21:33:44.161879

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1fd3b694fab"
down_revision: Union[str, None] = "b943530bccb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_to_word",
        sa.Column("users", sa.Integer(), nullable=True),
        sa.Column("words", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["users"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["words"],
            ["words.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_to_word")
    op.drop_table("words")
    # ### end Alembic commands ###
