"""empty message

Revision ID: a5320ef3ae3a
Revises: 4d699db6a18e
Create Date: 2023-11-09 19:55:28.568693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5320ef3ae3a'
down_revision: Union[str, None] = '4d699db6a18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
