"""empty message

Revision ID: b943530bccb6
Revises: 1fdf144223a0
Create Date: 2023-11-13 15:55:01.719092

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b943530bccb6"
down_revision: Union[str, None] = "1fdf144223a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("points", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "points")
    # ### end Alembic commands ###
