"""empty message

Revision ID: da3cc0807e73
Revises: a1fd3b694fab
Create Date: 2023-11-16 17:30:49.650186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3cc0807e73'
down_revision: Union[str, None] = 'a1fd3b694fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('translation', sa.String(), nullable=True))
    op.drop_column('words', 'link')
    op.drop_column('words', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('words', 'translation')
    # ### end Alembic commands ###
